mail:
  secretariaat: secretariaat@badminton-pbo.be
  jeugdcup: jeugdcup@badminton-pbo.be
  recreanten: recreanten@badminton-pbo.be
  voorzitter: voorzitter@badminton-pbo.be
social:
  - naam: Facebook
    link: https://www.facebook.com/PBO.Badminton
  - naam: Instagram
    link: https://www.instagram.com/pbobadminton/
  - naam: X / Twitter
    link: https://twitter.com/pbo_badm
sponsors:
  - naam: Mobi-sports
    link: https://mobi-sports.be/
    logo: ../../assets/sponsors/mobi-sports.png
competitie:
  agenda: https://competitie.badminton-pbo.be/agenda/
  uitslagen: https://badvla.tournamentsoftware.com/sport/league?id=F4D8C93E-D12D-4116-86CF-A63A6B9B6046
